server:
  port: 8088
  
spring:
  config:
    activate:
      on-profile: default
      
  application:
    name: consultador-peliculas

  datasource:
    username: postgres
    password: admin123
    url: jdbc:postgresql://localhost:5433/consultador-peliculas-db
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  kafka:
    properties:
      schema.registry.url: http://${schema-registry:localhost}:8081
      bootstrap-servers: ${kafka:localhost}:9092
        
  cloud:
    stream:
      bindings:
        peliculas_valoradas:
          content-type: application/avro
          destination: peliculas_valoradas
          consumer:
            useNativeDecoding: true
      kafka:
        binder:
          auto-create-topics: false
        streams:
          binder:
            stateStoreRetry:
              maxAttempts: 10
            configuration:
              state.dir: /tmp
              commit.interval.ms: 100
              topology.optimization: all
              session.timeout.ms: 10000
              schema.registry.url: http://schema-registry:8084
              auto.register.schemas: true
              default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        consumer:
          key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
          value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer