server:
  port: 8083

spring:
  application:
    name: enviador-valoraciones
  kafka:
    bootstrap-servers: ${kafka:localhost}:9092
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://${schema-registry:localhost}:8081
